const FLAGS = {
  "algeria": "🇩🇿",
  "argentina": "🇦🇷",
  "australia": "🇦🇺",
  "austria": "🇦🇹",
  "belgium": "🇧🇪",
  "brazil": "🇧🇷",
  "canada": "🇨🇦",
  "cape-verde": "🇨🇻",
  "colombia": "🇨🇴",
  "croatia": "🇭🇷",
  "curaao": "🇨🇼",
  "ecuador": "🇪🇨",
  "egypt": "🇪🇬",
  "england": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "france": "🇫🇷",
  "germany": "🇩🇪",
  "ghana": "🇬🇭",
  "haiti": "🇭🇹",
  "iran": "🇮🇷",
  "italy": "🇮🇹",
  "ivory-coast": "🇨🇮",
  "japan": "🇯🇵",
  "jordan": "🇯🇴",
  "mexico": "🇲🇽",
  "morocco": "🇲🇦",
  "netherlands": "🇳🇱",
  "new-zealand": "🇳🇿",
  "norway": "🇳🇴",
  "paraguay": "🇵🇾",
  "peru": "🇵🇪",
  "portugal": "🇵🇹",
  "qatar": "🇶🇦",
  "saudi-arabia": "🇸🇦",
  "scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "senegal": "🇸🇳",
  "south-africa": "🇿🇦",
  "south-korea": "🇰🇷",
  "spain": "🇪🇸",
  "switzerland": "🇨🇭",
  "tunisia": "🇹🇳",
  "uruguay": "🇺🇾",
  "usa": "🇺🇸",
  "uzbekistan": "🇺🇿",
};

export function getFlag(teamId) {
  return FLAGS[teamId] || "";
}
